theme: jekyll-theme-midnight

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Aaron Turon
url:                 http://aturon.github.io

# About/contact
author:
  name:              Aaron Turon
  email:             aturon@mozilla.com

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data", "smart"]

plugins: [github-pages]
